# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

stages:
- initialize-and-plan
- apply

terraform-plan:
  allow_failure: false
  stage: initialize-and-plan
  script:
    - terraform init
    - terraform plan 
    - exit 0

Deploy:
  stage: apply
  when: manual
  script:
  - terraform init
  - terraform apply 
  - terraform state list

